spring.application.name=HRAttritionPredictor

# PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_attrition_predictor
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=c2VjcmV0S2V5Rm9ySFJBdHRyaXRpb25QcmVkaWN0b3JTeXN0ZW0yMDI2
jwt.expiration=86400000



# ?????????????????????????????????????
# Mail Configuration
# ?????????????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hr.attrition.ooredoo@gmail.com
spring.mail.password=jfoadyvozxfdktdj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Email RH Ooredoo
app.mail.rh=hr.attrition.ooredoo@gmail.com
app.mail.from=hr.attrition.ooredoo@gmail.com

# URL du Mailing Server (port 8082)
notification.service.url=http://localhost:8082


# Dialecte explicite (évite le crash de détection automatique)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# HikariCP : réessayer indéfiniment au lieu de crasher
spring.datasource.hikari.initialization-fail-timeout=-1

# Timeouts
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10




