package com.ooredoo.hr.attrition.predictor.enums;

public enum EDepartment {
    DIRECTION_GENERALE,
    DIRECTION_RESSOURCES_HUMAINES,
    DIRECTION_ADMINISTRATIVE_FINANCIERE,
    DIRECTION_JURIDIQUE,
    DIRECTION_TECHNOLOGIQUE,
    DIRECTION_RELATIONS_OPERATEURS,
    DIRECTION_COMMERCIALE,
    DIRECTION_SERVICE_CLIENT,
    DIRECTION_SYSTEMES_INFORMATION,
    DIRECTION_OPERATIONS,
    DIRECTION_TECHNIQUE_FIXE,
    DIRECTION_INGENIERIE_RESEAUX,
    DEPARTEMENT_PERFORMANCE_RESEAUX,
    SERVICE_APPLICATION_VENTE,
    SERVICE_DATA_ENGINEERING,
    SERVICE_DASHBOARD_DATA_MINING
}