package com.ooredoo.hr.attrition.predictor.enums;

public enum EDepartment {
    DIRECTION_GENERALE,
    DIRECTION_RESSOURCES_HUMAINES,
    DIRECTION_ADMINISTRATIVE_FINANCIERE,
    DIRECTION_JURIDIQUE,
    DIRECTION_TECHNOLOGIQUE,
    DIRECTION_RELATIONS_OPERATEURS,
    DIRECTION_SERVICE_CLIENT
}